POST http://localhost:8080/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "sample@gmail.com",
    "username": "test",
    "password": "1234"
}

###

POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "email": "sample@gmail.com",
    "password": "1234"
}

###

POST http://localhost:8080/auth/free HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/world HTTP/1.1
content-type: application/json

{
}
